# Generated by Django 2.0.1 on 2018-02-26 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20180226_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 13, 48, 33, 751708)),
        ),
    ]
